version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bonos_user
      POSTGRES_PASSWORD: bonos_pass
      POSTGRES_DB: bonos_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
